### ISSUE TITLE
There is no manufacturer-specific EDS file available. Going on with the default dictionary...

### ISSUE THREAD

**Issue by grafoteka** [KITmedical/kacanopen#10]
Hi all, 

I'm trying to control 6 Mxon MCD Epos with the **kacanopen_example_motor_and_io_bridge** node. 
I have generate my EDS file with _Maxon EPOS Studio_ and then check it with _Vector CANeds_ program.

Then,  I copy the file into the path _/home/jorge/WS/kacanopen/src/kacanopen/master/share/eds_library/MaxonMotor_

And modify the **line 336 in the device.cpp** file with:

`std::string eds_path = "/home/jorge/WS/kacanopen/src/kacanopen/master/share/eds_library/MaxonMotor/maxon_motor_EPOS.eds";`

But when I execute:

`rosrun kacanopen kacanopen_example_motor_and_io_bridge`

I have the error:

`There is no manufacturer-specific EDS file available. Going on with the default dictionary...`

Am I doing something wrong importing the file?

Thank you, 
Jorge

**Comment by OliEfr** [comment]
Try to place your maxon_eds file in the location of CiA_profiles/402.eds

**Comment by grafoteka** [comment]
I try it OliEfr, but finally the problem is that is not possible to control the motor in velocity profile, they haven't implemented that mode...

Hope, someone could help me to do it

**Comment by thk1** [comment]
I'll close this, because the eds_library problem seems to be solved. If you want to, you can file a separate feature request for velocity mode support in the ros bridge. Unfortunately, I won't have time for this but maybe some else can help out...
