### ISSUE TITLE
SegFault by eds_library

### ISSUE THREAD

**Issue by magnifikus** [KITmedical/kacanopen#2]
gdb segfault:
Thread 1 "kacanopen_examp" received signal SIGSEGV, Segmentation fault.
0xb6aed9d4 in boost::filesystem::path::m_parent_path_end() const () from /usr/lib/arm-linux-gnueabihf/libboost_filesystem.so.1.58.0

happens for path: /root/kacanopen/kacanopen/master/share/eds_library/eds_files.json
by  https://github.com/KITmedical/kacanopen/blob/master/master/src/eds_library.cpp#L80

not sure why (cpp noob) but:
removing the file from the search paths and only adding the in the exist check works fine (saves the segfaulting line by just assigning path)

**Comment by thk1** [comment]
Could you please post a backtrace of this issue? I.e. enter "bt" in gdb after the segfault happened. What type of system do you use? I see you are on ARM? Any porting issues? Any changes to CMake files?
