### ISSUE TITLE
lot of CPU wasted in std::unordered_map::operator[]

### ISSUE THREAD

**Issue by facontidavide** [KITmedical/kacanopen#26]
Hi,

playing around with your library and profiling, I found a lot of CPU overhead that can be avoided in Device.

Is this library still actively supported/mainteined? If it is, do you want me to send a PR with the fix?

Regards

Davide

**Comment by roboticlemon** [comment]
Please do send a PR even if it's not maintained we might need to make a hard fork for a new one with new maintainers.

**Comment by facontidavide** [comment]
once you make the fork, I will send the PR there. Quite busy right now with something else

**Comment by roboticlemon** [comment]
For now we are probably going to work off @xdaco's fork at https://github.com/xdaco/kacanopen-fork . If you're busy just throw it up on a branch on your internal repo and we can take a look at it!

**Comment by xdaco** [comment]
@facontidavide Please send a PR at  https://github.com/xdaco/kacanopen-fork whenever you have time.

**Comment by facontidavide** [comment]
I have lost interest in this sorry. You can find relevant information here:

https://cpp-optimizations.netlify.app/boost_flatmap/
