### ISSUE TITLE
COB-ID limited to 16-bits

### ISSUE THREAD

**Issue by compiaffe** [KITmedical/kacanopen#3]
I am setting up an EPOS2/24 to send PDO messages on updates of its 'Position Actual Value' object.
In the firmware specification the COB-ID is specified as 32-bits long, but your add_receive_pdo_mapping or add_transmit_pdo_mapping expects a uint16_t . As long as the COB-ID all 0 in the 16 MSBs it works fine, however if it actually sets these bits it does not work.

This works:
``` c++
master.core.nmt.send_nmt_message(node_id,
                                     kaco::NMT::Command::enter_preoperational);
    device.set_entry(
        "Receive PDO 2 Mapping/Number of Mapped Application Objects in RxPDO 2",
        (uint8_t)0);
    device.set_entry("Receive PDO 2 Mapping/1st Mapped Object in RxPDO 2",
                     (uint32_t)0x607A0020);
    device.set_entry(
        "Receive PDO 2 Mapping/Number of Mapped Application Objects in RxPDO 2",
        (uint8_t)1);

    device.add_transmit_pdo_mapping(0x00000200 + node_id, {{"controlword", 0}});
    device.add_transmit_pdo_mapping(0x00000300 + node_id,
                                    {{"Target position", 0}});
    master.core.nmt.send_nmt_message(node_id, kaco::NMT::Command::start_node);

    device.execute("enable_operation_cached");
```
This does not:
``` c++
    master.core.nmt.send_nmt_message(node_id,
                                     kaco::NMT::Command::enter_preoperational);
    device.set_entry("Transmit PDO 2 Parameter/Inhibit Time", (uint16_t)20);
    device.set_entry("Transmit PDO 2 Mapping/Number of Mapped Application "
                     "Objects in TxPDO 2",
                     (uint8_t)1);
    device.set_entry("Transmit PDO 2 Mapping/1st Mapped Object in TxPDO 2",
                     (uint32_t)0x60640020);
    device.add_receive_pdo_mapping(0xC0000280 + node_id,
                                   "Position Actual Value", 0);
    master.core.nmt.send_nmt_message(node_id, kaco::NMT::Command::start_node);
    device.execute("enable_operation_cached");
```

I've tried to change all references to cob_id and the associated function calls to uint32_t but with that I cannot find any nodes any more.

Is there a way to use kacanopen to send 32-bit cob_ids?

**Comment by thk1** [comment]
Actually, COB-IDs are 11 bits long since CANopen is based on the CAN base frame format. See [Wikipedia](https://en.wikipedia.org/wiki/CANopen#Communication_objects) and CiA Draft Standard 301 v4.02 p.22. You should probably consider the [Predefined Connection Set](http://www.canopensolutions.com/english/about_canopen/predefined.shtml).
