### ISSUE TITLE
Shutdown hangs when PERIODIC transmit PDO mapping is active

### ISSUE THREAD

**Issue by tobijk** [KITmedical/kacanopen#5]
When there is an active PERIODIC transmit PDO mapping, then kacanopen will not shut down cleanly. I haven't found a way to stop the transmitter thread from the API. Is this a bug, or am I missing something?

**Comment by tobijk** [comment]
Possibly the transmitter thread should be detach'ed right from the beginning?

**Comment by thk1** [comment]
You are right, this seems to be a bug. Instead of detaching the thread, we should set a shutdown flag and then join. Would you mind testing the fix in branch issue5?

**Comment by tobijk** [comment]
Sure thing.

**Comment by tobijk** [comment]
Seems to work fine. Thanks!
